### ISSUE TITLE
Training works but model testing giving unexpected output. 

### ISSUE THREAD

**Issue by niqbal996** [artemsavkin/secogan#1]
Hi, 

I am trying to reproduce your code on my synthetic and real dataset of maize plants. I got promising training results with style transfer. However, now I want to generate high resolution transformed data based on the trained model. I only need **synthetic** (source) to **real** (target) transformed data. If i understand correctly i need to do:

```python
x_a = Variable(dataA).to(device)
x_b = Variable(dataB).to(device)
output = model(x_a, x_b, s_a, s_b)
x_aa, x_bb, x_ab, x_ba, x_aba, x_bab, pred_real_a, pred_real_b, pred_fake_ab, pred_fake_ba = output
```
where `x_ab` is my synthetic2real transformed image. 
I also tried something like this:
```python
s_b = torch.normal(0, 1, size=(1, 2 * 256)).repeat(opt.batch_size, 1).to(device)
shape = [-1, 2, 256, 1, 1]  # [-1, 2, channel, 1, 1]
s_b = s_b.view(shape)
c_a = model.encoder(x_a) 
x_ab = model.decoder(c_a, s_b)
```
In both cases, I get a blobby image as shown below:
![0025](https://github.com/artemsavkin/secogan/assets/28758769/60162d05-f0f5-4944-883b-26949748bfea)
However, the images generated during training look quite promising. 
![grid_epoch_187_crop](https://github.com/artemsavkin/secogan/assets/28758769/ebc9aaa8-9fe4-4d18-b3a9-056e84bd01da)
So I am guessing somehow my model weights loading is not functioning correctly. Here is how I load my model weights
https://github.com/niqbal996/secogan/blob/c09eaa6915db3205730ffda17e592503ee49fab5/model.py#L261 

and this is my testing script based on your `train.py`
https://github.com/niqbal996/secogan/blob/c09eaa6915db3205730ffda17e592503ee49fab5/train.py#L124C5-L139C109 
Any ideas what I might be doing wrong? and how to generated stylized images in the original image resolution so that I can feed it further into an object detection/segmentation network? Thank you. 
Any help will be appreciated.

**Comment by artemsavkin** [comment]
Dear @niqbal996 do you use the same `s_b` for inference as for training? If not you might need to store style vectors alongside with the model weights.

**Comment by niqbal996** [comment]
Hi @artemsavkin , 
Thank you for the quick response. You were right. I missed the loading of the style codes. Works like a charm now. I have the testing script here. If you want, I can submit a pull request. 
https://github.com/niqbal996/secogan/blob/main/test.py

**Comment by artemsavkin** [comment]
> 

@niqbal996 Glad it worked out. Sure feel free to do so!
